DEV-158 Agricultular Records features
eFarm-Manager/eFarm-backend pull request #75
Opened 2024-10-27 10:19 UTC by BartoszSkowyra22

Tasks DEV:
156-163,
166-169

2024-10-28 20:07 UTC, Sprysio reviewed
nie wszystko na 100% do zmiany co tam napisalem cos tam to sugestie czy pytania

2024-10-28 20:07 UTC, Sprysio commented on src/main/java/com/efarm/efarmbackend/controller/AgriculturalRecordController.java
funckcja dla /all nazywa sie getFarmEquipment

dla update area moze byc =0 teraz nwm czy chcemy zmieniac 
z tego co patrzylem powinno byc tez dla tworzenia

2024-10-29 15:47 UTC, BartoszSkowyra22 commented on src/main/java/com/efarm/efarmbackend/service/agriculturalrecords/SeasonService.java
Zmieniłem sezon na sierpień-lipiec, bo w sumie w sierpniu już się zaczyna siwe rzepaków itp. Więc dobrze, aby pod tym względem już dodawać nowe pola

2024-10-29 15:58 UTC, BartoszSkowyra22 commented on src/main/java/com/efarm/efarmbackend/controller/AgriculturalRecordController.java
Ja bym nie zezwalał na powierzchnię =0, bo w tedy oznacza to tyle, że tej uprawy nie ma. Więc raczej proponowałbym, aby wymuszać na użytkowniku usuwanie takiej uprawy, a nie na trzymaniu ewidencji z zerową powierzchnią

2024-10-29 21:02 UTC, Sprysio requested changes
Dodatkowo jezeli chodzi o tamtym update area w agricultural record to mi chodzilo ze w tym momencie mozna i stworzyc i update z area=0

![image](https://github.com/user-attachments/assets/53b51308-c1fb-44d4-8574-84346bdce4ab)

2024-10-31 14:52 UTC, Sprysio submitted a review, later dismissed

2024-10-31 14:52 UTC, Sprysio commented on src/main/java/com/efarm/efarmbackend/payload/request/agriculturalrecord/CreateNewAgriculturalRecordRequest.java
> +    @DecimalMin(value = "0.01", message = "Nie możesz podać wartości mniejszej niż 0.01 ha")
m2 nie ha

2024-10-31 14:52 UTC, Sprysio commented on src/main/java/com/efarm/efarmbackend/payload/request/agriculturalrecord/UpdateAgriculturalRecordRequest.java
> +    @DecimalMin(value = "0.01", message = "Nie możesz podać wartości mniejszej niż 0.01 ha")
m2 nie ha

2024-10-31 16:43 UTC, merged